name: Generate Book

on:
  push:
    branches: [ action ]
  pull_request:
    branches: [ action ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Download pages
      run: |
        investopedia --no-pdf https://www.investopedia.com/terms/i/irr.asp -o generated_investopedia_book.html
        ls -l
